export const SET_MOVIES = 'SET_MOVIES';
export const SET_FAVOURITE_MOVIES = 'SET_FAVOURITE_MOVIES';
export const REMOVE_FROM_FAVOURITE_MOVIES = 'REMOVE_FROM_FAVOURITE_MOVIES';
export const SET_PERSONS = 'SET_PERSONS';
export const SET_USER = 'SET_USER';
export const CLEAR_USER = 'CLEAR_USER';
export const SET_GENRES = 'SET_GENRES';
